// examples/solid-client/src/components/MessageLog.tsx
import { Component, createEffect, For } from 'solid-js';
import { messages } from '../stores/gameStore';

export const MessageLog: Component = () => {
  let logContainer: HTMLDivElement | undefined;

  createEffect(() => {
    messages(); // 依存関係追跡
    if (logContainer) {
      logContainer.scrollTop = logContainer.scrollHeight;
    }
  });

  return (
    <div class="message-log" ref={logContainer}>
      <For each={messages()}>
        {(msg) => <div class="log-line">{msg}</div>}
      </For>
    </div>
  );
};

// examples/svelte-client/src/components/MessageLog.svelte
<script lang="ts">
  import { afterUpdate } from 'svelte';
  import { messagesStore } from '../stores/gameStore';

  let logContainer: HTMLDivElement;

  afterUpdate(() => {
    if (logContainer) {
      logContainer.scrollTop = logContainer.scrollHeight;
    }
  });
</script>

<div class="message-log" bind:this={logContainer}>
  {#each $messagesStore as msg, index (index)}
    <div class="log-line">{msg}</div>
  {/each}
</div>
