// examples/react-client/src/components/AssistSignalBar.tsx
import React, { useState, useMemo, useCallback } from 'react';
import { useGameStore } from '../stores/gameStore';
import { useNetHackDriver } from '../hooks/useNetHackDriver';

export const AssistSignalBar: React.FC = () => {
  const [showWhyTooltip, setShowWhyTooltip] = useState(false);

  const isPlayerDead = useGameStore((state) => state.isPlayerDead);
  const engineState = useGameStore((state) => state.engineState);
  const hpMax = useGameStore((state) => state.status.hpMax);
  const gklSituation = useGameStore((state) => state.gklSituation);
  const currentLanguage = useGameStore((state) => state.currentLanguage);

  const { queueSequence, executeSequence } = useNetHackDriver();

  const isEn = currentLanguage === 'en';

  const assistState = useMemo(() => {
    if (isPlayerDead || engineState !== 'RUNNING' || hpMax <= 0) {
      return null;
    }
    return gklSituation?.assistState || null;
  }, [isPlayerDead, engineState, hpMax, gklSituation]);

  const primarySignal = useMemo(() => {
    if (isPlayerDead || engineState !== 'RUNNING' || hpMax <= 0) {
      return null;
    }
    return assistState?.primarySignal || null;
  }, [isPlayerDead, engineState, hpMax, assistState]);

  const primaryAction = useMemo(() => {
    return assistState?.primaryAction || null;
  }, [assistState]);

  const barSeverityClass = useMemo(() => {
    const sig = primarySignal;
    if (!sig) return '';
    if (sig.category === 'SURVIVAL' || (sig.priority && sig.priority >= 80)) {
      return 'danger';
    } else if (sig.priority && sig.priority >= 60) {
      return 'warning';
    } else if (sig.stance === 'CURE' || sig.category === 'TACTICAL_COMBAT') {
      return 'success';
    }
    return '';
  }, [primarySignal]);

  const signalText = useMemo(() => {
    const sig = primarySignal;
    if (!sig) return '';
    return isEn
      ? (sig.shortMessageEn || sig.shortMessageJa || '')
      : (sig.shortMessageJa || sig.shortMessageEn || '');
  }, [primarySignal, isEn]);

  const actionLabel = useMemo(() => {
    const act = primaryAction;
    if (!act) return isEn ? 'Execute' : '実行';
    return isEn
      ? (act.labelEn || act.labelJa || 'Execute')
      : (act.labelJa || act.labelEn || '実行');
  }, [primaryAction, isEn]);

  const whyText = useMemo(() => {
    const sig = primarySignal;
    if (!sig) return '';
    const text = isEn
      ? (sig.detailWhyEn || sig.detailWhyJa)
      : (sig.detailWhyJa || sig.detailWhyEn);
    return text || (isEn ? 'Recommended tactical move for survival.' : '生存率を高めるための推奨アクションです。');
  }, [primarySignal, isEn]);

  const handleExecuteAction = useCallback(async (e: React.MouseEvent) => {
    e.stopPropagation();
    const act = primaryAction;
    if (!act || !act.keySequence || act.keySequence.length === 0) return;

    const rawSeq = JSON.parse(JSON.stringify(act.keySequence));
    const res = await queueSequence(rawSeq);
    if (!res) {
      await executeSequence(rawSeq);
    }
  }, [primaryAction, queueSequence, executeSequence]);

  if (!primarySignal) return null;

  return (
    <div className={`assist-signal-bar ${barSeverityClass}`}>
      <div className="assist-signal-main">
        <span className="assist-signal-icon">{primarySignal.icon || '🛡️'}</span>
        <span className="assist-signal-text">{signalText}</span>
      </div>

      <div className="assist-signal-actions">
        {/* Level 3 ワンタップ実行ボタン */}
        {primaryAction && primaryAction.keySequence && primaryAction.keySequence.length > 0 && (
          <button
            className="btn btn-assist-action"
            onClick={handleExecuteAction}
          >
            <span className="assist-action-label">{actionLabel}</span>
          </button>
        )}

        {/* Why 理由解説ツールチップトグルボタン */}
        <button
          className="btn btn-assist-why"
          title="推奨理由を表示"
          onClick={(e) => {
            e.stopPropagation();
            setShowWhyTooltip((prev) => !prev);
          }}
        >
          ❓
        </button>
      </div>

      {/* Why 理由解説ツールチップ */}
      {showWhyTooltip && (
        <div className="assist-why-tooltip">
          {whyText}
        </div>
      )}
    </div>
  );
};

// examples/solid-client/src/components/AssistSignalBar.tsx
import { Component, Show, createSignal, createMemo } from 'solid-js';
import {
  isPlayerDead,
  engineState,
  status,
  gklSituation,
  currentLanguage
} from '../stores/gameStore';
import { driverController } from '../services/useNetHackDriver';

export const AssistSignalBar: Component = () => {
  const [showWhyTooltip, setShowWhyTooltip] = createSignal(false);

  const isEn = () => currentLanguage() === 'en';

  const assistState = createMemo(() => {
    if (isPlayerDead() || engineState() !== 'RUNNING' || status.hpMax <= 0) {
      return null;
    }
    return gklSituation()?.assistState || null;
  });

  const primarySignal = createMemo(() => {
    if (isPlayerDead() || engineState() !== 'RUNNING' || status.hpMax <= 0) {
      return null;
    }
    return assistState()?.primarySignal || null;
  });

  const primaryAction = createMemo(() => {
    return assistState()?.primaryAction || null;
  });

  const barSeverityClass = createMemo(() => {
    const sig = primarySignal();
    if (!sig) return '';
    if (sig.category === 'SURVIVAL' || (sig.priority && sig.priority >= 80)) {
      return 'danger';
    } else if (sig.priority && sig.priority >= 60) {
      return 'warning';
    } else if (sig.stance === 'CURE' || sig.category === 'TACTICAL_COMBAT') {
      return 'success';
    }
    return '';
  });

  const signalText = createMemo(() => {
    const sig = primarySignal();
    if (!sig) return '';
    return isEn()
      ? (sig.shortMessageEn || sig.shortMessageJa || '')
      : (sig.shortMessageJa || sig.shortMessageEn || '');
  });

  const actionLabel = createMemo(() => {
    const act = primaryAction();
    if (!act) return isEn() ? 'Execute' : '実行';
    return isEn()
      ? (act.labelEn || act.labelJa || 'Execute')
      : (act.labelJa || act.labelEn || '実行');
  });

  const whyText = createMemo(() => {
    const sig = primarySignal();
    if (!sig) return '';
    const text = isEn()
      ? (sig.detailWhyEn || sig.detailWhyJa)
      : (sig.detailWhyJa || sig.detailWhyEn);
    return text || (isEn() ? 'Recommended tactical move for survival.' : '生存率を高めるための推奨アクションです。');
  });

  const handleExecuteAction = (e: MouseEvent) => {
    e.stopPropagation();
    const act = primaryAction();
    if (!act || !act.keySequence || act.keySequence.length === 0) return;

    const rawSeq = JSON.parse(JSON.stringify(act.keySequence));
    driverController.executeSequence(rawSeq);
  };

  return (
    <Show when={primarySignal()}>
      <div class={`assist-signal-bar ${barSeverityClass()}`}>
        <div class="assist-signal-main">
          <span class="assist-signal-icon">{primarySignal()?.icon || '🛡️'}</span>
          <span class="assist-signal-text">{signalText()}</span>
        </div>

        <div class="assist-signal-actions">
          {/* Level 3 ワンタップ実行ボタン */}
          <Show when={primaryAction() && primaryAction()?.keySequence && primaryAction()?.keySequence.length > 0}>
            <button
              class="btn btn-assist-action"
              onClick={handleExecuteAction}
              title={whyText()}
            >
              ⚡ {actionLabel()}
            </button>
          </Show>

          {/* 理由ポップオーバー */}
          <button
            class="btn-assist-why"
            onClick={(e) => {
              e.stopPropagation();
              setShowWhyTooltip(!showWhyTooltip());
            }}
            title={isEn() ? 'Why this action?' : 'なぜこの行動？'}
          >
            ❓
          </button>
        </div>

        <Show when={showWhyTooltip()}>
          <div class="assist-why-tooltip">
            <strong>💡 {isEn() ? 'Tactical Reasoning:' : '状況推論と理由:'}</strong>
            <p style={{ margin: '4px 0 0 0' }}>{whyText()}</p>
          </div>
        </Show>
      </div>
    </Show>
  );
};
