// examples/react-client/src/components/ContextActions.tsx
import React, { useState, useMemo, useCallback } from 'react';
import { useGameStore } from '../stores/gameStore';
import { useNetHackDriver } from '../hooks/useNetHackDriver';
import { DirectionPad } from './DirectionPad';

export const ContextActions: React.FC = () => {
  const [selectedDir, setSelectedDir] = useState<string>('ALL');

  const gklSituation = useGameStore((state) => state.gklSituation);
  const currentLanguage = useGameStore((state) => state.currentLanguage);

  const { extractDirectionCode, getDefaultAction, executeSequence, executeAction } = useNetHackDriver();

  const isEn = currentLanguage === 'en';

  const rawActions = useMemo(() => {
    return gklSituation?.actions || gklSituation?.contextActions || [];
  }, [gklSituation]);

  const actionCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const act of rawActions) {
      const dir = extractDirectionCode(act);
      if (dir && dir !== 'NONE') {
        counts[dir] = (counts[dir] || 0) + 1;
      }
    }
    return counts;
  }, [rawActions, extractDirectionCode]);

  const filteredActions = useMemo(() => {
    if (selectedDir === 'ALL') {
      return rawActions;
    }
    const filtered = rawActions.filter((act: any) => {
      const dir = extractDirectionCode(act);
      return dir === selectedDir;
    });

    // 方向選択時に対象アクションが 0件 または 1件 の場合、デフォルト推奨アクション（待機 または 移動/押す）を追加
    if (filtered.length <= 1 && typeof getDefaultAction === 'function') {
      const defaultAct = getDefaultAction(selectedDir);
      if (defaultAct && !filtered.some((a: any) => a.id === defaultAct.id)) {
        return [...filtered, defaultAct];
      }
    }

    return filtered;
  }, [rawActions, selectedDir, extractDirectionCode, getDefaultAction]);

  const getActionItemClass = (act: any): string => {
    if (act.category === 'SURVIVAL' || act.isEmergency || act.severity === 'CRITICAL') {
      return 'danger';
    }
    if (act.category === 'TACTICAL_COMBAT' || act.type === 'ATTACK') {
      return 'combat';
    }
    return '';
  };

  const getKeys = (act: any): string[] => {
    if (Array.isArray(act.keySequence) && act.keySequence.length > 0) {
      return act.keySequence;
    }
    if (act.key) return [act.key];
    if (act.keys) return Array.isArray(act.keys) ? act.keys : [act.keys];
    return [];
  };

  const handleActionClick = useCallback(async (act: any) => {
    if (act.actionRecipe) {
      await executeSequence(act.actionRecipe);
    } else if (act.keySequence && Array.isArray(act.keySequence) && act.keySequence.length > 0) {
      await executeSequence(act.keySequence);
    } else {
      executeAction(act);
    }
  }, [executeSequence, executeAction]);

  return (
    <div className="gkl-card actions-card">
      <div className="gkl-card-header">
        <span>🧠 {isEn ? 'Context Actions' : '推奨アクション (ContextActions)'}</span>
        <span className="gkl-badge">{filteredActions.length}</span>
      </div>

      {/* 🎯 方向フィルターインジケーター (「囲」型 3x3 キーパッド) */}
      <DirectionPad
        value={selectedDir}
        onChange={setSelectedDir}
        actionCounts={actionCounts}
      />

      {/* 推奨アクションリスト */}
      <div className="gkl-action-list">
        {filteredActions.length === 0 ? (
          <div className="gkl-empty-hint">
            {isEn ? 'No contextual actions available' : '周辺環境に応じたアクションが自動表示されます'}
          </div>
        ) : (
          filteredActions.map((act: any, idx: number) => (
            <div
              key={act.id || idx}
              className={`gkl-action-item ${getActionItemClass(act)}`}
              onClick={() => handleActionClick(act)}
            >
              <div className="act-main">
                <span className="act-icon">{act.icon || '⚡'}</span>
                <div className="act-info">
                  <div className="act-label">
                    {isEn ? (act.labelEn || act.label || act.name) : (act.labelJa || act.label || act.name)}
                  </div>
                  {(act.description || act.desc || act.descriptionEn || act.descriptionJa) && (
                    <div className="act-desc">
                      {isEn
                        ? (act.descriptionEn || act.descEn || act.description || act.desc)
                        : (act.descriptionJa || act.descJa || act.description || act.desc)}
                    </div>
                  )}
                </div>
              </div>

              <div className="act-keys">
                {getKeys(act).map((k, kIdx) => (
                  <span key={kIdx} className="act-key-badge">
                    {k}
                  </span>
                ))}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

// examples/solid-client/src/components/ContextActions.tsx
import { Component, createSignal, createMemo, Show, For } from 'solid-js';
import { gklSituation, currentLanguage } from '../stores/gameStore';
import { driverController } from '../services/useNetHackDriver';
import { DirectionPad } from './DirectionPad';

export const ContextActions: Component = () => {
  const [selectedDir, setSelectedDir] = createSignal<string>('ALL');

  const isEn = () => currentLanguage() === 'en';

  const rawActions = createMemo(() => {
    return gklSituation()?.actions || gklSituation()?.contextActions || [];
  });

  const actionCounts = createMemo(() => {
    const counts: Record<string, number> = {};
    for (const act of rawActions()) {
      const dir = driverController.extractDirectionCode(act);
      if (dir && dir !== 'NONE') {
        counts[dir] = (counts[dir] || 0) + 1;
      }
    }
    return counts;
  });

  const filteredActions = createMemo(() => {
    const dir = selectedDir();
    if (dir === 'ALL') {
      return rawActions();
    }
    const filtered = rawActions().filter((act: any) => {
      const d = driverController.extractDirectionCode(act);
      return d === dir;
    });

    // 方向選択時に対象アクションが 0件 または 1件 の場合、デフォルト推奨アクション（待機 または 移動/押す）を追加
    if (filtered.length <= 1 && typeof driverController.getDefaultAction === 'function') {
      const defaultAct = driverController.getDefaultAction(dir);
      if (defaultAct && !filtered.some((a: any) => a.id === defaultAct.id)) {
        return [...filtered, defaultAct];
      }
    }

    return filtered;
  });


  const getActionItemClass = (act: any): string => {
    if (act.category === 'SURVIVAL' || act.isEmergency || act.severity === 'CRITICAL') {
      return 'danger';
    }
    if (act.category === 'TACTICAL_COMBAT' || act.type === 'ATTACK') {
      return 'combat';
    }
    return '';
  };

  const getKeys = (act: any): string[] => {
    if (Array.isArray(act.keySequence) && act.keySequence.length > 0) {
      return act.keySequence;
    }
    if (act.key) return [act.key];
    if (act.keys) return Array.isArray(act.keys) ? act.keys : [act.keys];
    return [];
  };

  const handleActionClick = (act: any) => {
    if (act.actionRecipe) {
      driverController.executeSequence(act.actionRecipe);
    } else if (act.keySequence && Array.isArray(act.keySequence) && act.keySequence.length > 0) {
      driverController.executeSequence(act.keySequence);
    } else {
      driverController.executeAction(act);
    }
  };

  return (
    <div class="gkl-card actions-card">
      <div class="gkl-card-header">
        <span>🧠 {isEn() ? 'Context Actions' : '推奨アクション (ContextActions)'}</span>
        <span class="gkl-badge">{filteredActions().length}</span>
      </div>

      {/* 🎯 方向フィルターインジケーター (「囲」型 3x3 キーパッド) */}
      <DirectionPad
        value={selectedDir()}
        onChange={setSelectedDir}
        actionCounts={actionCounts()}
      />

      {/* 推奨アクションリスト */}
      <div class="gkl-action-list">
        <Show
          when={filteredActions().length > 0}
          fallback={
            <div class="gkl-empty-hint">
              {isEn() ? 'No contextual actions available' : '周辺環境に応じたアクションが自動表示されます'}
            </div>
          }
        >
          <For each={filteredActions()}>
            {(act: any, idx) => (
              <div
                class={`gkl-action-item ${getActionItemClass(act)}`}
                onClick={() => handleActionClick(act)}
              >
                <div class="act-main">
                  <span class="act-icon">{act.icon || '⚡'}</span>
                  <div class="act-info">
                    <div class="act-label">
                      {isEn() ? (act.labelEn || act.label || act.name) : (act.labelJa || act.label || act.name)}
                    </div>
                    <Show when={act.description || act.desc}>
                      <div class="act-desc">{act.description || act.desc}</div>
                    </Show>
                  </div>
                </div>

                <div class="act-keys">
                  <For each={getKeys(act)}>
                    {(key) => (
                      <span class="act-key-badge">{key}</span>
                    )}
                  </For>
                </div>
              </div>
            )}
          </For>
        </Show>
      </div>
    </div>
  );
};
