// examples/vue-client/src/components/MenuModal.vue
<template>
  <div v-if="activeMenu" class="modal-backdrop">
    <div class="modal-content">
      <h3 class="modal-title">{{ activeMenu.prompt || 'Select Item' }}</h3>

      <div class="menu-list" ref="menuListRef">
        <div
          v-for="(item, idx) in activeMenu.items"
          :key="idx"
          class="menu-item-row"
          :class="{ 
            'menu-header': item.isHeader,
            'selected': selectedIndices.includes(idx),
            'focused': focusedIndex === idx
          }"
          @click="handleItemClick(idx, item)"
        >
          <!-- 1. アクセラレータキー (a), b), c)...) -->
          <span class="item-acc" v-if="getAccChar(item)">
            {{ getAccChar(item) }})
          </span>

          <!-- 2. 正確な CSS Sprite タイル表示 -->
          <span
            v-if="getTileStyle(item)"
            class="item-tile"
            :style="getTileStyle(item)"
          ></span>

          <!-- 3. アイテム文字列 -->
          <span class="item-str">{{ item.str }}</span>
        </div>
      </div>

      <div class="modal-footer">
        <template v-if="activeMenu.how === 0">
          <button @click="cancelMenu" class="btn btn-primary">OK (Enter / Space / ESC)</button>
        </template>
        <template v-else>
          <button @click="confirmSelection" class="btn btn-primary">OK (Enter)</button>
          <button @click="cancelMenu" class="btn btn-secondary">Cancel (ESC)</button>
        </template>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, nextTick } from 'vue';
import { useGameStore } from '../stores/gameStore';
import { storeToRefs } from 'pinia';
import { useNetHackDriver } from '../composables/useNetHackDriver';
import { getTileMapping } from '../utils/tileMapping';

const gameStore = useGameStore();
const { activeMenu } = storeToRefs(gameStore);
const { respondMenu } = useNetHackDriver();

const selectedIndices = ref<number[]>([]);
const focusedIndex = ref<number>(-1);
const isSubmitting = ref(false);
const menuListRef = ref<HTMLElement | null>(null);
let tileMapTable: Record<number, number> = {};

onMounted(() => {
  tileMapTable = getTileMapping();
  window.addEventListener('keydown', handleKeyDown, true);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown, true);
});

watch(activeMenu, (newVal) => {
  if (newVal) {
    selectedIndices.value = [];
    isSubmitting.value = false;
    const firstSelectable = newVal.items.findIndex(it => !it.isHeader && (it.identifier !== undefined && it.identifier !== 0));
    focusedIndex.value = firstSelectable >= 0 ? firstSelectable : -1;
  }
});

function getAccChar(item: any): string {
  if (item.isHeader) return '';
  const ch = item.accelerator !== undefined && item.accelerator !== 0 ? item.accelerator : item.ch;
  if (typeof ch === 'string' && ch !== '\x00') return ch;
  if (typeof ch === 'number' && ch > 0) return String.fromCharCode(ch);
  return '';
}

function getTileStyle(item: any): string {
  if (item.isHeader) return '';
  const glyph = item.glyph !== undefined ? item.glyph : (item.glyphInfo?.glyph ?? -1);
  if (glyph < 0 || !tileMapTable) return '';

  const tileIdx = tileMapTable[glyph];
  if (tileIdx === undefined || tileIdx < 0) return '';

  const tilesPerRow = 40;
  const origTileSize = 32;
  const tx = (tileIdx % tilesPerRow) * origTileSize;
  const ty = Math.floor(tileIdx / tilesPerRow) * origTileSize;

  const posX = -(tx / 2);
  const posY = -(ty / 2);

  return `background-image: url(./pict/nethack_default_32.png); background-position: ${posX}px ${posY}px; background-size: 640px auto; width: 16px; height: 16px; min-width: 16px; min-height: 16px; flex-shrink: 0; display: inline-block; image-rendering: pixelated; margin-right: 6px; background-repeat: no-repeat; vertical-align: middle;`;
}

function safeRespondMenu(val: any) {
  if (isSubmitting.value) return;
  isSubmitting.value = true;
  respondMenu(val);
}

function handleItemClick(idx: number, item: any) {
  if (item.isHeader || isSubmitting.value) return;
  focusedIndex.value = idx;
  const how = activeMenu.value?.how ?? 1;

  if (how === 0) {
    safeRespondMenu(0);
    return;
  }

  if (how === 1) {
    safeRespondMenu([item]);
    return;
  }

  const pos = selectedIndices.value.indexOf(idx);
  if (pos > -1) {
    selectedIndices.value.splice(pos, 1);
  } else {
    selectedIndices.value.push(idx);
  }
}

function confirmSelection() {
  if (!activeMenu.value || isSubmitting.value) return;

  if (activeMenu.value.how === 0) {
    safeRespondMenu(0);
    return;
  }

  if (selectedIndices.value.length > 0) {
    const selectedItems = selectedIndices.value.map(
      (idx) => activeMenu.value!.items[idx]
    );
    safeRespondMenu(selectedItems);
  } else if (focusedIndex.value >= 0 && !activeMenu.value.items[focusedIndex.value]?.isHeader) {
    const item = activeMenu.value.items[focusedIndex.value];
    safeRespondMenu([item]);
  } else {
    const validItem = activeMenu.value.items.find(
      (it: any) => !it.isHeader && it.identifier !== undefined && it.identifier !== 0
    );
    safeRespondMenu(validItem ? [validItem] : 0);
  }
}

function cancelMenu() {
  if (isSubmitting.value) return;
  safeRespondMenu(0);
}

function moveFocus(delta: number) {
  if (!activeMenu.value || activeMenu.value.items.length === 0) return;
  const items = activeMenu.value.items;
  let nextIdx = focusedIndex.value + delta;

  while (nextIdx >= 0 && nextIdx < items.length) {
    if (!items[nextIdx].isHeader && items[nextIdx].identifier !== 0) {
      focusedIndex.value = nextIdx;
      scrollToFocused();
      return;
    }
    nextIdx += delta;
  }
}

function scrollToFocused() {
  nextTick(() => {
    if (!menuListRef.value) return;
    const focusedEl = menuListRef.value.querySelector('.focused') as HTMLElement;
    if (focusedEl) {
      focusedEl.scrollIntoView({ block: 'nearest' });
    }
  });
}

function handleKeyDown(e: KeyboardEvent) {
  if (!activeMenu.value || isSubmitting.value) return;

  if (e.key === 'ArrowUp') {
    e.preventDefault();
    e.stopPropagation();
    moveFocus(-1);
    return;
  }

  if (e.key === 'ArrowDown') {
    e.preventDefault();
    e.stopPropagation();
    moveFocus(1);
    return;
  }

  if (e.key === 'Escape' || (activeMenu.value.how === 0 && (e.key === ' ' || e.key === 'Enter'))) {
    e.preventDefault();
    e.stopPropagation();
    cancelMenu();
    return;
  }

  if (e.key === 'Enter') {
    e.preventDefault();
    e.stopPropagation();
    confirmSelection();
    return;
  }

  // アクセラレータキーのキーボード直接選択 (a-z, A-Z, 0-9 等)
  if (e.key.length === 1 && activeMenu.value.how !== 0) {
    const pressedKey = e.key;
    const pressedCode = e.key.charCodeAt(0);

    const matchIdx = activeMenu.value.items.findIndex((it: any) => {
      if (it.isHeader) return false;
      const c = getAccChar(it);
      if (c && c === pressedKey) return true;
      if (c && c.toLowerCase() === pressedKey.toLowerCase()) return true;
      if (typeof it.accelerator === 'number' && it.accelerator === pressedCode) return true;
      return false;
    });

    if (matchIdx >= 0) {
      e.preventDefault();
      e.stopPropagation();
      const matchItem = activeMenu.value.items[matchIdx];
      const how = activeMenu.value.how ?? 1;
      if (how === 1) {
        safeRespondMenu([matchItem]);
      } else {
        handleItemClick(matchIdx, matchItem);
      }
    }
  }
}
</script>

<style scoped>
.modal-backdrop {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.8);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background: #16213e;
  border: 2px solid #0f3460;
  border-radius: 8px;
  width: 550px;
  max-width: 92vw;
  max-height: 82vh;
  display: flex;
  flex-direction: column;
  padding: 16px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.9);
  color: #e94560;
}

.modal-title {
  margin: 0 0 10px 0;
  color: #4ecca3;
  font-size: 18px;
  border-bottom: 1px solid #0f3460;
  padding-bottom: 8px;
}

.menu-list {
  flex-grow: 1;
  overflow-y: auto;
  margin: 8px 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.menu-item-row {
  padding: 6px 10px;
  border-radius: 4px;
  cursor: pointer;
  background: #1a1a2e;
  display: flex;
  align-items: center;
  gap: 10px;
  color: #e0e0e0;
  font-family: monospace;
  border: 1px solid transparent;
}

.menu-item-row:hover:not(.menu-header) {
  background: #0f3460;
  color: #ffffff;
}

.menu-item-row.focused:not(.menu-header) {
  border-color: #4ecca3;
  background: #162a45;
  box-shadow: 0 0 5px rgba(78, 204, 163, 0.5);
}

.menu-item-row.selected {
  background: #4ecca3;
  color: #111111;
  font-weight: bold;
}

.menu-header {
  font-weight: bold;
  color: #f39c12;
  background: transparent;
  cursor: default;
  padding-top: 8px;
  border-bottom: 1px dashed #333;
}

.item-acc {
  color: #f39c12;
  font-weight: bold;
  min-width: 24px;
}

.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  border-top: 1px solid #0f3460;
  padding-top: 12px;
}

.btn {
  padding: 6px 14px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-weight: bold;
}

.btn-primary { background: #4ecca3; color: #111; }
.btn-secondary { background: #555; color: #fff; }
</style>

// examples/solid-client/src/components/MenuModal.tsx
import { Component, createSignal, createEffect, onMount, onCleanup, Show, For } from 'solid-js';
import { activeMenu, MenuItem } from '../stores/gameStore';
import { driverController } from '../services/useNetHackDriver';
import { getTileMapping } from '../utils/tileMapping';

export const MenuModal: Component = () => {
  const [selectedIndices, setSelectedIndices] = createSignal<number[]>([]);
  const [focusedIndex, setFocusedIndex] = createSignal<number>(-1);
  let isSubmitting = false;
  let tileMapTable: Record<number, number> = {};
  let menuListRef: HTMLDivElement | undefined;

  createEffect(() => {
    const menu = activeMenu();
    if (menu) {
      setSelectedIndices([]);
      isSubmitting = false;
      tileMapTable = getTileMapping();
      const firstSelectable = menu.items.findIndex((it) => !it.isHeader && (it.identifier !== undefined && it.identifier !== 0));
      setFocusedIndex(firstSelectable >= 0 ? firstSelectable : -1);
    }
  });

  const getAccChar = (item: MenuItem): string => {
    if (item.isHeader) return '';
    const ch = item.accelerator !== undefined && item.accelerator !== 0 ? item.accelerator : item.ch;
    if (typeof ch === 'string' && ch !== '\x00') return ch;
    if (typeof ch === 'number' && ch > 0) return String.fromCharCode(ch);
    return '';
  };

  const getTileStyle = (item: MenuItem): string => {
    if (item.isHeader) return '';
    const glyph = item.glyph !== undefined ? item.glyph : (item.glyphInfo?.glyph ?? -1);
    if (glyph < 0 || !tileMapTable) return '';

    const tileIdx = tileMapTable[glyph];
    if (tileIdx === undefined || tileIdx < 0) return '';

    const tilesPerRow = 40;
    const origTileSize = 32;
    const tx = (tileIdx % tilesPerRow) * origTileSize;
    const ty = Math.floor(tileIdx / tilesPerRow) * origTileSize;

    const posX = -(tx / 2);
    const posY = -(ty / 2);

    return `background-image: url(./pict/nethack_default_32.png); background-position: ${posX}px ${posY}px; background-size: 640px auto; width: 16px; height: 16px; min-width: 16px; min-height: 16px; flex-shrink: 0; display: inline-block; image-rendering: pixelated; margin-right: 6px; background-repeat: no-repeat; vertical-align: middle;`;
  };

  const safeRespondMenu = (val: any) => {
    if (isSubmitting) return;
    isSubmitting = true;
    driverController.respondMenu(val);
  };

  const handleItemClick = (idx: number, item: MenuItem) => {
    const menu = activeMenu();
    if (!menu || item.isHeader || isSubmitting) return;
    setFocusedIndex(idx);
    const how = menu.how ?? 1;

    if (how === 0) {
      safeRespondMenu(0);
      return;
    }

    if (how === 1) {
      safeRespondMenu([item]);
      return;
    }

    setSelectedIndices((prev) => {
      if (prev.includes(idx)) {
        return prev.filter((i) => i !== idx);
      } else {
        return [...prev, idx];
      }
    });
  };

  const confirmSelection = () => {
    const menu = activeMenu();
    if (!menu || isSubmitting) return;

    if (menu.how === 0) {
      safeRespondMenu(0);
      return;
    }

    const indices = selectedIndices();
    const focusIdx = focusedIndex();
    if (indices.length > 0) {
      const selectedItems = indices.map((idx) => menu.items[idx]);
      safeRespondMenu(selectedItems);
    } else if (focusIdx >= 0 && !menu.items[focusIdx]?.isHeader) {
      const item = menu.items[focusIdx];
      safeRespondMenu([item]);
    } else {
      const validItem = menu.items.find(
        (it: MenuItem) => !it.isHeader && it.identifier !== undefined && it.identifier !== 0
      );
      safeRespondMenu(validItem ? [validItem] : 0);
    }
  };

  const cancelMenu = () => {
    if (isSubmitting) return;
    safeRespondMenu(0);
  };

  const moveFocus = (delta: number) => {
    const menu = activeMenu();
    if (!menu || menu.items.length === 0) return;
    const items = menu.items;
    let current = focusedIndex();
    let nextIdx = current + delta;

    while (nextIdx >= 0 && nextIdx < items.length) {
      if (!items[nextIdx].isHeader && items[nextIdx].identifier !== 0) {
        setFocusedIndex(nextIdx);
        setTimeout(() => {
          const focusedEl = menuListRef?.querySelector('.focused') as HTMLElement;
          if (focusedEl) focusedEl.scrollIntoView({ block: 'nearest' });
        }, 0);
        return;
      }
      nextIdx += delta;
    }
  };

  onMount(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const menu = activeMenu();
      if (!menu || isSubmitting) return;

      if (e.key === 'ArrowUp') {
        e.preventDefault();
        e.stopPropagation();
        moveFocus(-1);
        return;
      }

      if (e.key === 'ArrowDown') {
        e.preventDefault();
        e.stopPropagation();
        moveFocus(1);
        return;
      }

      if (e.key === 'Escape' || (menu.how === 0 && (e.key === ' ' || e.key === 'Enter'))) {
        e.preventDefault();
        e.stopPropagation();
        cancelMenu();
        return;
      }

      if (e.key === 'Enter') {
        e.preventDefault();
        e.stopPropagation();
        confirmSelection();
        return;
      }

      if (e.key.length === 1 && menu.how !== 0) {
        const pressedKey = e.key;
        const pressedCode = e.key.charCodeAt(0);

        const matchIdx = menu.items.findIndex((it: MenuItem) => {
          if (it.isHeader) return false;
          const c = getAccChar(it);
          if (c && c === pressedKey) return true;
          if (c && c.toLowerCase() === pressedKey.toLowerCase()) return true;
          if (typeof it.accelerator === 'number' && it.accelerator === pressedCode) return true;
          return false;
        });

        if (matchIdx >= 0) {
          e.preventDefault();
          e.stopPropagation();
          const matchItem = menu.items[matchIdx];
          const how = menu.how ?? 1;
          if (how === 1) {
            safeRespondMenu([matchItem]);
          } else {
            handleItemClick(matchIdx, matchItem);
          }
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown, true);
    onCleanup(() => {
      window.removeEventListener('keydown', handleKeyDown, true);
    });
  });

  return (
    <Show when={activeMenu()}>
      {(menu) => (
        <div class="modal-backdrop" onClick={cancelMenu}>
          <div class="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3 class="modal-title">{menu().prompt || 'Select Item'}</h3>

            <div class="menu-list" ref={menuListRef}>
              <For each={menu().items}>
                {(item, idx) => {
                  const accChar = getAccChar(item);
                  const tileStyle = getTileStyle(item);
                  const isSelected = () => selectedIndices().includes(idx());
                  const isFocused = () => focusedIndex() === idx();

                  return (
                    <Show
                      when={!item.isHeader && item.identifier !== undefined && item.identifier !== 0}
                      fallback={
                        <div class="menu-item-row menu-header">{item.str}</div>
                      }
                    >
                      <div
                        class={`menu-item-row ${isSelected() ? 'selected' : ''} ${isFocused() ? 'focused' : ''}`}
                        onClick={() => handleItemClick(idx(), item)}
                      >
                        <Show when={accChar}>
                          <span class="item-acc">{accChar})</span>
                        </Show>
                        <Show when={tileStyle}>
                          <span class="item-tile" style={tileStyle}></span>
                        </Show>
                        <span class="item-str">{item.str}</span>
                      </div>
                    </Show>
                  );
                }}
              </For>
            </div>

            <div class="modal-footer">
              <Show
                when={menu().how !== 0}
                fallback={
                  <button onClick={cancelMenu} class="btn btn-primary">
                    OK (Enter / Space / ESC)
                  </button>
                }
              >
                <button onClick={confirmSelection} class="btn btn-primary">
                  OK (Enter)
                </button>
                <button onClick={cancelMenu} class="btn btn-secondary">
                  Cancel (ESC)
                </button>
              </Show>
            </div>
          </div>
        </div>
      )}
    </Show>
  );
};
