// examples/react-client/src/components/TextWindowModal.tsx
import React, { useEffect, useCallback } from 'react';
import { useGameStore } from '../stores/gameStore';

export const TextWindowModal: React.FC = () => {
  const activeTextModal = useGameStore((state) => state.activeTextModal);
  const setTextModal = useGameStore((state) => state.setTextModal);

  const closeTextModal = useCallback(() => {
    if (activeTextModal && activeTextModal.resolver) {
      const res = activeTextModal.resolver;
      setTextModal(null);
      res.respond(0);
    }
  }, [activeTextModal, setTextModal]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!activeTextModal) return;

      if (e.key === 'Escape' || e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        e.stopPropagation();
        closeTextModal();
      }
    };

    window.addEventListener('keydown', handleKeyDown, true);
    return () => {
      window.removeEventListener('keydown', handleKeyDown, true);
    };
  }, [activeTextModal, closeTextModal]);

  if (!activeTextModal) return null;

  return (
    <div className="modal-backdrop">
      <div className="modal-content">
        <h3 className="modal-title">{activeTextModal.title || 'Information / Help'}</h3>

        <div className="text-body">
          {activeTextModal.lines.map((line, idx) => (
            <div key={idx} className="text-line">
              {line}
            </div>
          ))}
        </div>

        <div className="modal-footer">
          <button onClick={closeTextModal} className="btn btn-primary">
            OK (Enter / Space / ESC)
          </button>
        </div>
      </div>
    </div>
  );
};

// examples/solid-client/src/components/TextWindowModal.tsx
import { Component, onMount, onCleanup, Show, For } from 'solid-js';
import { activeTextModal, setActiveTextModal } from '../stores/gameStore';

export const TextWindowModal: Component = () => {
  const handleClose = () => {
    const modal = activeTextModal();
    if (modal && modal.resolver) {
      const res = modal.resolver;
      setActiveTextModal(null);
      res.respond(0);
    } else {
      setActiveTextModal(null);
    }
  };

  onMount(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!activeTextModal()) return;

      if (e.key === 'Escape' || e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        e.stopPropagation();
        handleClose();
      }
    };

    window.addEventListener('keydown', handleKeyDown, true);
    onCleanup(() => {
      window.removeEventListener('keydown', handleKeyDown, true);
    });
  });

  return (
    <Show when={activeTextModal()}>
      {(modal) => (
        <div class="modal-backdrop" onClick={handleClose}>
          <div class="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3 class="modal-title">{modal().title || 'Information'}</h3>

            <div class="text-body">
              <For each={modal().lines}>
                {(line) => <div class="text-line">{line}</div>}
              </For>
            </div>

            <div class="modal-footer">
              <button onClick={handleClose} class="btn btn-primary">
                OK (Space / Enter / ESC)
              </button>
            </div>
          </div>
        </div>
      )}
    </Show>
  );
};
