// examples/solid-client/src/components/MessageLog.tsx
import { Component, createEffect, For } from 'solid-js';
import { messages } from '../stores/gameStore';

export const MessageLog: Component = () => {
  let logContainer: HTMLDivElement | undefined;

  createEffect(() => {
    messages(); // 依存関係追跡
    if (logContainer) {
      logContainer.scrollTop = logContainer.scrollHeight;
    }
  });

  return (
    <div class="message-log" ref={logContainer}>
      <For each={messages()}>
        {(msg) => <div class="log-line">{msg}</div>}
      </For>
    </div>
  );
};

// examples/react-client/src/components/MessageLog.tsx
import React, { useRef, useEffect } from 'react';
import { useGameStore } from '../stores/gameStore';

export const MessageLog: React.FC = () => {
  const messages = useGameStore((state) => state.messages);
  const logContainerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (logContainerRef.current) {
      logContainerRef.current.scrollTop = logContainerRef.current.scrollHeight;
    }
  }, [messages]);

  return (
    <div className="message-log" ref={logContainerRef}>
      {messages.map((msg, index) => (
        <div key={index} className="log-line">
          {msg}
        </div>
      ))}
    </div>
  );
};
